### ISSUE TITLE
small typo, if the socket was not yet consumed, socket.destroy throws exception

### ISSUE THREAD

**Issue by mh-cbon** [mafintosh/multicast-dns#30]
Hi,

there s a small typo in the destroy method.

If the socket has not yet send any message,
it is not yet open,
thus, if destroy is invoked,
it throws an exception such

```js
dgram.js:461
    throw new Error('Not running'); // error message from dgram_legacy.js
    ^

Error: Not running
    at Socket._healthCheck (dgram.js:461:11)
    at Socket.close (dgram.js:354:8)
    at EventEmitter.that.destroy (/home/mh-cbon/projects/bonjour-over-http/node_modules/multicast-dns/index.js:106:12)
    at Bonjour.destroy (/home/mh-cbon/projects/bonjour-over-http/node_modules/bonjour/index.js:38:21)
    at Object.destroy (/home/mh-cbon/projects/bonjour-over-http/index.js:133:15)
    at process.tearDown (/home/mh-cbon/projects/bonjour-over-http/bin.js:117:15)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
```

**Comment by watson** [comment]
I just tried to check this. This is my observation: The first time `destroy` is called it doesn't fail, but the 2nd time it's called it fails with the mentioned error.

My gut feeling is that this should be expected behaviour. I can't rule out though if the bonjour module have a bug where it calls it multiple times. Can you share what you did to get it to fail?

**Comment by mafintosh** [comment]
i pushed a fix yesterday where double destroy doesn't throw (6.0.1). if you have a test case that shows that this is still an issue feel free to post it here and re-open

**Comment by mh-cbon** [comment]
indeed, forcing module update fix the problem, and yeah i believe i misread your code (...missed the call to bind in middle of the code... only saw the one within send). 

To reproduce you should install and configure `npm i mh-cbon/bonjour-over-http -g`, then start it, then ctrl+c.

I will wait `bonjour` is updated to the latest `multicast-dns` dependency.

Thanks both of you.
