### ISSUE TITLE
Error: addMembership ENOBUFS  

### ISSUE THREAD

**Issue by sdockray** [mafintosh/multicast-dns#39]
This error has started in the last 2 weeks on one particular machine and I'm not sure why. I have seen it in dat-next and dat-next-next.. the excerpts below are from trying to do a simple clone. I used the same key on a different machine and both worked fine, so it's an issue with the environment not the key.

Some info on the machine that I see the problem occurring on:

```
 lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.7 (jessie)
Release:        8.7
Codename:       jessie

uname -mrs
Linux 4.10.13-feral x86_64

npm list -g dat-next
└── dat-next@3.2.4 

npm list -g dat-next-next
└── dat-next-next@0.0.24 

```

error with dat-next

```
dat-next <key> <dir>    
Starting Dat program...    
    
events.js:160    
      throw er; // Unhandled 'error' event    
      ^    
    
Error: addMembership ENOBUFS    
    at exports._errnoException (util.js:1022:11)    
    at Socket.addMembership (dgram.js:508:11)    
    at Socket.<anonymous> (/path/to/node_modules/dat-next/node_modules/multicast-dns/index.js:53:16)    
    at emitNone (events.js:91:20)    
    at Socket.emit (events.js:185:7)    
    at startListening (dgram.js:121:10)    
    at dgram.js:228:7    
    at _combinedTickCallback (internal/process/next_tick.js:77:11)    
    at process._tickCallback (internal/process/next_tick.js:98:9) 
```

and with dat-next-next

```
 dat-next-next <key>
Syncing dat ...
Key is: <key>
Downloading at 0 B/s, Uploading at 0 B (0 peers)
events.js:160
      throw er; // Unhandled 'error' event
lo              1      ff02::1
bond0           1      ff02::1
Key is: <key>   
Downloading at 0 B/s, Uploading at 0 B (0 peers)    
events.js:160    
      throw er; // Unhandled 'error' event    
      ^    
    
Error: addMembership ENOBUFS    
    at exports._errnoException (util.js:1022:11)    
    at Socket.addMembership (dgram.js:508:11)    
    at Socket.<anonymous> (/path/to/node_modules/dat-next-next/node_modules/multicast-dns/index.js:53:16)    
    at emitNone (events.js:91:20)    
    at Socket.emit (events.js:185:7)    
    at startListening (dgram.js:121:10)    
    at dgram.js:228:7    
    at _combinedTickCallback (internal/process/next_tick.js:77:11)    
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by mafintosh** [comment]
I think this is fixed in latest...
