### ISSUE TITLE
Windows 10 Bash on Windows Error: addMembership EINVAL

### ISSUE THREAD

**Issue by yaananth** [mafintosh/multicast-dns#45]
```

events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: addMembership EINVAL
    at exports._errnoException (util.js:1050:11)
    at Socket.addMembership (dgram.js:502:11)
    at Socket.<anonymous> (/mnt/e/test/node_modules/multicast-dns/index.js:53:16)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:188:7)
    at startListening (dgram.js:117:10)
    at _handle.lookup (dgram.js:222:7)
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

https://github.com/webpack/webpack-dev-server/issues/955 looks kind of similar but that's for `webpack-dev-server.js` which I am not using.

**Comment by yaananth** [comment]
Actually, looks like dup of https://github.com/Microsoft/BashOnWindows/issues/2245#issuecomment-310546134
