### ISSUE TITLE
crash when multiple ip on same interface

### ISSUE THREAD

**Issue by thosil** [mafintosh/multicast-dns#46]
When there are multiple IPs defined on the same interface, multicast-dns crash with this error:
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: addMembership EADDRINUSE
    at exports._errnoException (util.js:1020:11)
    at Socket.addMembership (dgram.js:506:11)
    at Socket.<anonymous> (/home/tsi/projects/multicast-dns/index.js:57:18)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at startListening (dgram.js:121:10)
    at _handle.lookup (dgram.js:226:7)
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
npm ERR! Test failed.  See above for more details.
```
It appears with version 6.2.0.
Problem is that socket.addMembership() could only be done [once per interface](https://nodejs.org/api/dgram.html#dgram_socket_addmembership_multicastaddress_multicastinterface)
And the function allInterfaces() return all IPs regardless of the interface they belongs to.
I'll provide shortly a PR.

**Comment by mafintosh** [comment]
Ah, right. Will wait for your PR

**Comment by thosil** [comment]
I'm facing problems with the tests: option multicast must be enabled to test the issue, but the "dns" is not listening itself and the test case "works" wait indefinitely.
I'll send you the PR anyways, and maybe you can understand better what I mean.

**Comment by mafintosh** [comment]
fixed by you
