### ISSUE TITLE
macOS: Cannot decode name (bad pointer)

### ISSUE THREAD

**Issue by lstrojny** [mafintosh/multicast-dns#82]
I am getting this error on Mac:

```
  Error: Cannot decode name (bad pointer)
      at name.decode (…/node_modules/dns-packet/index.js:83:15)
      at rnsec.decode (…/node_modules/dns-packet/index.js:1147:28)
      at answer.decode (…/node_modules/dns-packet/index.js:1451:18)
      at decodeList (…/node_modules/dns-packet/index.js:1625:19)
      at exports.decode (…/node_modules/dns-packet/index.js:1566:12)
      at Socket.<anonymous> (…/node_modules/multicast-dns/index.js:40:24)
      at Socket.emit (node:events:513:28)
      at UDP.onMessage [as onmessage] (node:dgram:930:8)```
```

This is the packet in hex:

```
000084000000000600000000045f686170045f746370056c6f63616c00000c000100001194001411496e646f6f7243616d20324b2d30413143c00c09496e646f6f7263616dc016002f8001000000780005c0a5000140c027002f8001000011940009c02700050000800040c03b00018001000000780004c0a801f3c0270021800100000078000800000000b6f8c03bc0270010800100001194004c0463233d310466663d321469643d34413a34413a33373a37383a34443a3030086d643d54383430300670763d312e310573233d31340473663d300563693d31370b73683d4a6b6e5466773d3d
```

The service that is advertised in the broken package just works fine on Linux.

**Comment by lstrojny** [comment]
Turns out, this was a local setup issue. Details [here](https://github.com/mafintosh/dns-packet/issues/84#issuecomment-1311588674)
